apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: 'trueberryless/blog:'
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
  annotations:
    cert-manager.io/issuer: acme-issuer
spec:
  selector:
    app: blog
  ports:
    - name: http
      port: 80
  template:
    spec:
      containers:
        - image: 'trueberryless/blog:'
