apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog
  namespace: blog
spec:
  secretName: blog
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'blog.trueberryless.org'
