apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
  labels:
    app: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: 'trueberryless/blog:main-08212b8b96a9fb3aa791597221c0b7bfc8459ab1'
          imagePullPolicy: Always
