name: Convert to British English

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"
  push:
    branches: main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run conversion script
        run: python scripts/convert_to_british.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Convert American spellings to British spellings"
          branch: british-spellings
          title: "Convert American to British English in docs"
          body: "This PR converts American spellings in ./starlight/src/content/docs to British spellings based on our mapping."
          delete-branch: true
