name: Convert to British English

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"
  push:
    branches: main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13.6"

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run conversion script
        run: python scripts/convert_to_british.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          commit-message: "Convert American spellings to British spellings"
          branch: british-spellings
          title: "Convert American to British English in docs"
          body: "This PR converts American spellings in ./starlight/src/content/docs to British spellings based on our mapping."
          delete-branch: true
