name: Build Test

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: trueberryless/mutanuq
  NODE_VERSION: 18

jobs:
  try-build:
    name: Run install and build
    defaults:
      run:
        working-directory: './starlight'
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Dependencies
        run: pnpm i
      
      - name: Astro Build
        run: pnpm run build

  # pa11y:
  #   name: Check for accessibility issues
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Setup PNPM
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8

  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'pnpm'

  #     - name: Install Dependencies
  #       working-directory: ./starlight
  #       run: pnpm i

  #     - name: Build docs site
  #       working-directory: ./starlight
  #       run: pnpm build
  #       env:
  #         NO_GRADIENTS: true

  #     - name: Run accessibility audit
  #       working-directory: ./starlight
  #       run: pnpm t

  # windows-smoke:
  #   name: Docs site builds on Windows
  #   runs-on: windows-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v3
        
  #     - name: Setup PNPM
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8
      
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'pnpm'
        
  #     - name: Install Dependencies
  #       working-directory: ./starlight
  #       run: pnpm i
      
  #     - name: Build docs site
  #       working-directory: ./starlight
  #       run: pnpm build
